### ISSUE TITLE
Waterfill crashes everytime it's placed

### ISSUE THREAD

**Issue by alexzander700** [RitnDev/RitnWaterfill#1]
Waterfill (1.4.4) caused a non-recoverable error every time I try placing waterfill. 
![image](https://github.com/RitnDev/RitnWaterfill/assets/51793351/9bf2b2cb-df4b-4b9a-aaa5-412b8979e6ce)
I can share the mods I am using if that helps, however I am using the latest version as of May 20th, 2024

**Comment by alexzander700** [comment]
This happens whether the land is paved or not.

**Comment by RitnDev** [comment]
Sorry I only just saw your issue on my mod, I no longer look at the messages in the "Discussion" tab of my mods.

I just fixed it with version 1.4.5.

thx.
